config/routes.rb
FFC::Application.routes.draw do

  resources :drafts

  root "leagues#index"

  post "/addpick" => "drafts#add_pick"

  get "/keepers" => "recruits#keepers"

  get "/simdraft" => "drafts#predict_draft"

  get "/livedraft" => "drafts#live_draft"

  get '/drafts/:league_id/new_draft' => "drafts#new_draft"

  post "/drafts/:league_id/init_draft" => "drafts#initialize_draft"

  get "/leagues/:league/recruits" => "leagues#list_recruits"

  get "/add_recruits/:league_id" => "leagues#add_recruits_to_league"

  post "/upload_recruits/:league_id" => "recruits#upload_recruits"

  post "create_league_teams/:league_id" => "teams#create_league_teams"

  post "initialize_teams/:league_id"  => 'teams#initialize_teams'

  resources :demands

  resources :franchises

  resources :plays

  resources :recruits

  resources :positions

  resources :leagues

  resources :teams

  resources :players

end

app/models/demand.rb
class Demand < ActiveRecord::Base

	belongs_to :league

end

app/models/draft.rb
class Draft < ActiveRecord::Base

	belongs_to :league
	has_many :orders, dependent: :destroy
	has_many :picks, dependent: :destroy
	has_many :players, through: :picks
end

app/models/franchise.rb
class Franchise < ActiveRecord::Base

	# might be a redundant table
end

app/models/league.rb
class League < ActiveRecord::Base
	validates :name, :presence=>true, :uniqueness=>true	

	has_many :teams, dependent: :destroy
	has_many :drafts, dependent: :destroy
	has_many :recruits, through: :teams, dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :draft
	has_one :team
end

app/models/pick.rb
class Pick < ActiveRecord::Base

	belongs_to :draft
	has_one :team
	has_one :player
end

app/models/play.rb
class Play < ActiveRecord::Base

	has_one :position
	has_one :player

	# if not using position table, this is not necessary

end

app/models/player.rb
class Player < ActiveRecord::Base

	validates :name, :presence=>true, :uniqueness=>true	
	has_many :recruits, dependent: :destroy
end

app/models/position.rb
class Position < ActiveRecord::Base

	# not currently using
end

app/models/recruit.rb
class Recruit < ActiveRecord::Base

	validates :player_id, uniqueness: { scope: :league_id }

	belongs_to :player
	belongs_to :team
	has_many :players


end

app/models/team.rb
class Team < ActiveRecord::Base

	belongs_to :league
	has_many :recruits, dependent: :destroy
	has_many :players, through: :recruits
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    league_id = params[:id]

    @teams = Team.where(:league_id => league_id)

  end

  def add_recruits_to_league
    @league = params[:league_id]
  end


  def list_recruits
    @league_id = params[:league]

    @recruits = Recruit.where(:league_id => @league_id).order('projected_points desc') 
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render action: 'show', status: :created, location: @league }
      else
        format.html { render action: 'new' }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name)
    end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :set_play, only: [:show, :edit, :update, :destroy]

  # GET /plays
  # GET /plays.json
  def index
    @plays = Play.all
  end

  # GET /plays/1
  # GET /plays/1.json
  def show
  end

  # GET /plays/new
  def new
    @play = Play.new
  end

  # GET /plays/1/edit
  def edit
  end

  # POST /plays
  # POST /plays.json
  def create
    @play = Play.new(play_params)

    respond_to do |format|
      if @play.save
        format.html { redirect_to @play, notice: 'Play was successfully created.' }
        format.json { render action: 'show', status: :created, location: @play }
      else
        format.html { render action: 'new' }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plays/1
  # PATCH/PUT /plays/1.json
  def update
    respond_to do |format|
      if @play.update(play_params)
        format.html { redirect_to @play, notice: 'Play was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.json
  def destroy
    @play.destroy
    respond_to do |format|
      format.html { redirect_to plays_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play
      @play = Play.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_params
      params.require(:play).permit(:integer, :integer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/franchises_helper.rb
module FranchisesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/add_recruits_to_league.html.erb
<%= form_tag("/upload_recruits/#{@league}", multipart: true) do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<br><br>

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render 'form' %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<h1>Listing leagues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.name %></td>
        <td><%= link_to 'Show', league %></td>
        <td><%= link_to 'Edit', edit_league_path(league) %></td>
        <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New League', new_league_path %>

app/views/leagues/list_recruits.html.erb
<h3><%= "Recruits for " + League.find_by(:id => @league_id).name %></h3>

<% @recruits.each do |recruit| %>
	<%= Player.find_by(:id => recruit.player_id).name + ", Points: " + recruit.projected_points.to_s %><br>
<% end %>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <strong><%= @league.name %></strong>
</h3>

<%= link_to 'Start New Draft Companion', "/drafts/#{@league.id}/new_draft" %><br><br>

<table>
  	<thead>
	    <tr>
	      <th>Team</th>
	      <th></th>
	      <th></th>
	    </tr>
 	</thead>

	<tbody>
		<% @teams.each do |team| %>		
  			<tr>
				<td><%= team.name%></td>
			    <td><%= link_to 'Show', team %></td>
				<td><%= link_to 'Edit', edit_team_path(team) %></td>
			</tr>
		<% end %>
	</tbody>
</table><br>

<strong><%= "Add New Teams:" %></strong>
<%= form_tag "/initialize_teams/#{@league.id}", :method => 'post' do %>
	<div class="field">
	  <%= label_tag "num_teams" %>
	  <%= text_field_tag "num_teams" %>
	</div>
	<div class="actions">
		<%= submit_tag "Enter Number of Teams" %>
	</div>
<% end %><br><br>

<%= link_to 'Show Recruits', "/leagues/#{@league.id}/recruits" %><br><br>
<%= link_to 'Upload Recruits', "/add_recruits/#{@league.id}" %><br><br>
<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %>