config/routes.rb
FFC::Application.routes.draw do

  resources :drafts

  root "leagues#index"

  post "/addpick" => "drafts#add_pick"

  get "/keepers" => "recruits#keepers"

  get "/simdraft" => "drafts#predict_draft"

  get "/livedraft" => "drafts#live_draft"

  get '/drafts/:league_id/new_draft' => "drafts#new_draft"

  post "/drafts/:league_id/init_draft" => "drafts#initialize_draft"

  get "/leagues/:league/recruits" => "leagues#list_recruits"

  get "/add_recruits/:league_id" => "leagues#add_recruits_to_league"

  post "/upload_recruits/:league_id" => "recruits#upload_recruits"

  post "create_league_teams/:league_id" => "teams#create_league_teams"

  post "initialize_teams/:league_id"  => 'teams#initialize_teams'

  resources :demands

  resources :franchises

  resources :plays

  resources :recruits

  resources :positions

  resources :leagues

  resources :teams

  resources :players

end

app/models/demand.rb
class Demand < ActiveRecord::Base

	belongs_to :league

end

app/models/draft.rb
class Draft < ActiveRecord::Base

	belongs_to :league
	has_many :orders, dependent: :destroy
	has_many :picks, dependent: :destroy
	has_many :players, through: :picks
end

app/models/franchise.rb
class Franchise < ActiveRecord::Base

	# might be a redundant table
end

app/models/league.rb
class League < ActiveRecord::Base
	validates :name, :presence=>true, :uniqueness=>true	

	has_many :teams, dependent: :destroy
	has_many :drafts, dependent: :destroy
	has_many :recruits, through: :teams, dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :draft
	has_one :team
end

app/models/pick.rb
class Pick < ActiveRecord::Base

	belongs_to :draft
	has_one :team
	has_one :player
end

app/models/play.rb
class Play < ActiveRecord::Base

	has_one :position
	has_one :player

	# if not using position table, this is not necessary

end

app/models/player.rb
class Player < ActiveRecord::Base

	validates :name, :presence=>true, :uniqueness=>true	
	has_many :recruits, dependent: :destroy
end

app/models/position.rb
class Position < ActiveRecord::Base

	# not currently using
end

app/models/recruit.rb
class Recruit < ActiveRecord::Base

	validates :player_id, uniqueness: { scope: :league_id }

	belongs_to :player
	belongs_to :team
	has_many :players


end

app/models/team.rb
class Team < ActiveRecord::Base

	belongs_to :league
	has_many :recruits, dependent: :destroy
	has_many :players, through: :recruits
end

app/controllers/demands_controller.rb
class DemandsController < ApplicationController
  before_action :set_demand, only: [:show, :edit, :update, :destroy]

  # GET /demands
  # GET /demands.json
  def index
    @demands = Demand.all
  end

  # GET /demands/1
  # GET /demands/1.json
  def show
  end

  # GET /demands/new
  def new
    @demand = Demand.new
  end

  # GET /demands/1/edit
  def edit
  end

  # POST /demands
  # POST /demands.json
  def create
    @demand = Demand.new(demand_params)

    respond_to do |format|
      if @demand.save
        format.html { redirect_to @demand, notice: 'Demand was successfully created.' }
        format.json { render action: 'show', status: :created, location: @demand }
      else
        format.html { render action: 'new' }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demands/1
  # PATCH/PUT /demands/1.json
  def update
    respond_to do |format|
      if @demand.update(demand_params)
        format.html { redirect_to @demand, notice: 'Demand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demands/1
  # DELETE /demands/1.json
  def destroy
    @demand.destroy
    respond_to do |format|
      format.html { redirect_to demands_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demand
      @demand = Demand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demand_params
      params.require(:demand).permit(:integer, :integer, :integer, :integer)
    end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :set_play, only: [:show, :edit, :update, :destroy]

  # GET /plays
  # GET /plays.json
  def index
    @plays = Play.all
  end

  # GET /plays/1
  # GET /plays/1.json
  def show
  end

  # GET /plays/new
  def new
    @play = Play.new
  end

  # GET /plays/1/edit
  def edit
  end

  # POST /plays
  # POST /plays.json
  def create
    @play = Play.new(play_params)

    respond_to do |format|
      if @play.save
        format.html { redirect_to @play, notice: 'Play was successfully created.' }
        format.json { render action: 'show', status: :created, location: @play }
      else
        format.html { render action: 'new' }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plays/1
  # PATCH/PUT /plays/1.json
  def update
    respond_to do |format|
      if @play.update(play_params)
        format.html { redirect_to @play, notice: 'Play was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.json
  def destroy
    @play.destroy
    respond_to do |format|
      format.html { redirect_to plays_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play
      @play = Play.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_params
      params.require(:play).permit(:integer, :integer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/franchises_helper.rb
module FranchisesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/demands/_form.html.erb
<%= form_for(@demand) do |f| %>
  <% if @demand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demand.errors.count, "error") %> prohibited this demand from being saved:</h2>

      <ul>
      <% @demand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/demands/edit.html.erb
<h1>Editing demand</h1>

<%= render 'form' %>

<%= link_to 'Show', @demand %> |
<%= link_to 'Back', demands_path %>

app/views/demands/index.html.erb
<h1>Listing demands</h1>

<table>
  <thead>
    <tr>
      <th>Integer</th>
      <th>Integer</th>
      <th>Integer</th>
      <th>Integer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @demands.each do |demand| %>
      <tr>
        <td><%= demand.integer %></td>
        <td><%= demand.integer %></td>
        <td><%= demand.integer %></td>
        <td><%= demand.integer %></td>
        <td><%= link_to 'Show', demand %></td>
        <td><%= link_to 'Edit', edit_demand_path(demand) %></td>
        <td><%= link_to 'Destroy', demand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demand', new_demand_path %>

app/views/demands/new.html.erb
<h1>New demand</h1>

<%= render 'form' %>

<%= link_to 'Back', demands_path %>

app/views/demands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Integer:</strong>
  <%= @demand.integer %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @demand.integer %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @demand.integer %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @demand.integer %>
</p>

<%= link_to 'Edit', edit_demand_path(@demand) %> |
<%= link_to 'Back', demands_path %>