config/routes.rb
FFC::Application.routes.draw do

  resources :drafts

  root "leagues#index"

  post "/addpick" => "drafts#add_pick"

  get "/keepers" => "recruits#keepers"

  get "/simdraft" => "drafts#predict_draft"

  get "/livedraft" => "drafts#live_draft"

  get '/drafts/:league_id/new_draft' => "drafts#new_draft"

  post "/drafts/:league_id/init_draft" => "drafts#initialize_draft"

  get "/leagues/:league/recruits" => "leagues#list_recruits"

  get "/add_recruits/:league_id" => "leagues#add_recruits_to_league"

  post "/upload_recruits/:league_id" => "recruits#upload_recruits"

  post "create_league_teams/:league_id" => "teams#create_league_teams"

  post "initialize_teams/:league_id"  => 'teams#initialize_teams'

  resources :demands

  resources :franchises

  resources :plays

  resources :recruits

  resources :positions

  resources :leagues

  resources :teams

  resources :players

end

app/models/draft.rb
class Draft < ActiveRecord::Base

	belongs_to :league
	has_many :orders, dependent: :destroy
	has_many :picks, dependent: :destroy
	has_many :players, through: :picks
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :set_draft, only: [:show, :edit, :update, :destroy]

  # GET /drafts
  # GET /drafts.json
  def index
    @drafts = Draft.all
  end

  def keepers
    @keepers = Recruit.where(:league_id => session[:league_id]).where('last_year_points > 0')
  end

  def new_draft
    @league_id = params[:league_id]
    @teams = Team.where(:league_id => @league_id)
  end

  def add_pick  

    player_name = params[:player]
    player_like = "%#{player_name}%"
    @players_found = Player.where("lower(name) LIKE ?", player_like.downcase)

    if @players_found.size == 1
      player = @players_found.first

      testpick = Pick.where(:draft_id => session[:draft_id]).find_by(:player_id => player.id)

      if testpick.nil?      
        team, round = find_team_by_pick_num(session[:pick_number])
        team = Team.find_by(:name => team)

        pick = Pick.new
        pick.draft_id = session[:draft_id]
        pick.pick_num = session[:pick_number]
        pick.team_id = team.id
        pick.player_id = player.id
        pick.round = round
        pick.save      

        session[:pick_number] += 1

        @message = "Player Found"
      else
        @message = "Player already drafted in this draft!"
      end
      #elsif need errors
    elsif @players_found.size == 0
      @message = "No Players Found"
    elsif @players_found.size > 1
      @message = "More than one player found" 

      @players_found.each do |player|
        @message = @message + "||||||" + player.name.to_s
      end
    end

    @picks = Pick.where(:draft_id => session[:draft_id])            

    while (session[:pick_number] <= 200) && (!@picks.find_by(:pick_num => session[:pick_number]).nil?)
      session[:pick_number] += 1
    end    

    initialize_simulation(session[:draft_id], @picks)    

  end

  def initialize_draft
    # intialize teams
    draft_name = params[:draft_name]
    draft_type = params[:draft_type]
    league_id = params[:league_id].to_i
    team_id = params[:my_team].to_i
    my_team = Team.find_by(:id => team_id).name
    rounds = params[:number_of_rounds].to_i
    keepers = params[:draft_trades]
    draft_trades = params[:draft_trades]
    
    # league = League.find_by(:name => "Speeding Utility Ram")
    session[:league_id] = league_id
    @teams = Team.where(:league_id => league_id) 
    session[:num_teams] = @teams.size
    # rounds = 20 
    session[:rounds] = rounds
    # session[:myteam] = "Team 1 - Me"
    session[:myteam] = my_team
    session[:num_picks] = @teams.count * session[:rounds]
    session[:pick_number] = 1

    # olddraft = Draft.find_by(:name => "CDW-Symantec Draft")

    # if !olddraft.nil?
    #   Pick.where(:draft_id => olddraft.id).destroy_all
    #   olddraft.destroy
    # end

    # draft = Draft.new
    # draft.name = "Speeding Utility 2014"
    # draft.draft_type = "Snake"
    # draft.league_id = league.id
    # draft.num_rounds = 20
    # draft.save

    draft = Draft.new
    draft.name = draft_name
    draft.draft_type = draft_type
    draft.league_id = league_id
    draft.num_rounds = rounds
    draft.save

    draft_order = []

    @teams.each do |team|
      index = params[team.id.to_s].to_i
      draft_order[index-1] = team.name
    end


    session[:draft_id] = draft.id

    #initialize array of picks
    session[:draft_order] = draft_order
    # session[:draft_trades] = { ["Team 4 - Matt", 16] => "Team 2 - Tim", ["Team 2 - Tim", 7] => "Team 4 - Matt", ["Team 2 - Tim", 10] => "Team 4 - Matt", ["Team 8 - JD", 8] => "Team 1 - Me", ["Team 1 - Me", 13] => "Team 8 - JD" }

    session[:draft_trades] = {}


    @keepers = []

    # positions
    # session[:num_starters] = { "QB" => 1, "RB" => 2, "WR" => 2, "TE" => 1, "FLEX" => 1, "LB" => 1, "DL" => 1, "DB" => 1, "K" => 1, "HC" => 1 }
    # session[:max_per_position] = { "QB" => 2, "RB" => 5, "WR" => 5, "TE" => 2, "FLEX" => nil, "LB" => 3, "DL" => 4, "DB" => 4, "K" => 3, "HC" => 2, "BENCH" => 8, "IR" => 2 }    
    session[:num_starters] = { "QB" => 1, "RB" => 2, "WR" => 2, "TE" => 1, "FLEX" => 1, "K" => 1, "DEF" => 1 }
    session[:max_per_position] = { "QB" => 5, "RB" => 5, "WR" => 5, "TE" => 5, "FLEX" => nil, "K" => 3, "DEF" => 3, "BENCH" => 5 }
    @picks = Pick.where(:draft_id => session[:draft_id])

    # initialize available players
    # queue players
    players = Recruit.where(:league_id => session[:league_id]).order('projected_points desc')
    # @qbs, @rbs, @wrs, @tes, @lbs, @dls, @dbs, @ks, @hcs = queue_players(players)    
    # queues = { "QB" => @qbs, "RB" => @rbs, "WR" => @wrs, "TE" => @tes, "LB" => @lbs, "DL" => @dls, "DB" => @dbs, "K" => @ks, "HC" => @hcs }
    # @qbs, @rbs, @wrs, @tes, @ks, @defs = queue_players(players)    
    @queues = queue_players(players) #{ "QB" => @qbs, "RB" => @rbs, "WR" => @wrs, "TE" => @tes, "K" => @ks, "DEF" => @defs }

    @num_players_per_position = initialize_players_per_position(@teams, session[:num_starters])        

    # @keepers = ["Drew Brees", "A.J. Green", "Victor Cruz", "Dez Bryant", "DeMarco Murray",
    #   "Michael Crabtree", "Matt Forte", "Calvin Johnson", "Jay Cutler", "Rashad Jennings", "Julius Thomas", 
    #   "Demaryius Thomas", "Rob Gronkowski", "Stephen Gostkowski", "Eddie Lacy", "Marshawn Lynch", "Jamaal Charles", "Greg Olsen",
    #   "Adrian Peterson", "Brandon Marshall", "Giovani Bernard", "Percy Harvin", "Jordan Cameron", "Peyton Manning", "Julio Jones",
    #   "LeSean McCoy", "Mike Wallace", "Colin Kaepernick", "Doug Martin", "Jimmy Graham", "Le'Veon Bell", "Zac Stacy", "Eagles Coach",
    #   "Aaron Rodgers", "Vernon Davis", "DeSean Jackson", "Alshon Jeffery", "Montee Ball"]    

    initialize_picks(session[:draft_order], draft.draft_type, @keepers, @queues, @num_players_per_position)    

    initialize_simulation(draft.id, @picks)

  end

  def initialize_picks(draft_order, draft_type, keepers, queues, players_per_position)
    if draft_type == "Snake" 
      ascending = true
      pick_order = 1  
      round = 1

      @keeper_picks = initialize_keeper_picks(keepers)

      for pick in 1..session[:num_picks]

        index = pick_order - 1
        team = draft_order[index]

        keeper = @keeper_picks[[round,team]]

        if !keeper.nil?
          # @picks[[pick,team.id]] = keeper.name

          # move to method create_new_pick
          pick_new = Pick.new
          pick_new.draft_id = session[:draft_id]
          pick_new.pick_num = pick
          pick_new.team_id = team.id
          pick_new.player_id = keeper.id 
          pick_new.round = round
          pick_new.save

          # update position counts
          player = Player.find_by(:name => keeper.name)
          position = player.position
          index = team.name + position
          # @num_players_per_position[index] += 1

          #remove player from available player queue
          remove_player_from_queue(keeper.name, draft_order[index], queues, players_per_position)
        end

        # change draft order
        if ascending & (pick_order < session[:num_teams])
          pick_order += 1
        elsif ascending
          ascending = false
          round += 1
        elsif !ascending & (pick_order > 1)
          pick_order -= 1
        else
          ascending = true
          round += 1
        end     
      end 


    end

  end

  def remove_player_from_queue(player, position, team, queues, players_per_position)

    # establish flexkey
    key = team + position
    flexkey = team + "FLEX"

    queues[position].delete(player)

    # check if need to update flex
    if (position == "RB" || position == "WR" || position == "TE") 
      num = players_per_position[key]

      if ((num == session[:num_starters][position]) && (players_per_position[flexkey] == 0))
        players_per_position[flexkey] = 1
      end
    end

    players_per_position[key] += 1
 
  end

  def initialize_keeper_picks(keepers)
    keeper_picks = Hash.new

    keepers.each do |keeper|
      player_info = Player.find_by(:name => keeper)
      position = player_info.position
      player_name = player_info.name
      pick = Pick.find_by(:player_id => player_info.id) 
      recruit = Recruit.where(:league_id => session[:league_id]).find_by(:player_id => player_info.id)
      team = Team.find_by(:id => recruit.team_id).name

      if (pick.nil?) || (pick.round == session[:rounds])
        round = session[:rounds]
      else
        round = (pick.round + 1)
      end   

      keeper_picks[[round,team]] = player_info

    end

    return keeper_picks

  end

  def initialize_players_per_position(teams, positions)
    num_players_per_position = Hash.new(0)

    teams.each do |team|
      positions.each do |position, num|
        string = team.name + position

        num_players_per_position[string] = 0
      end
    end    

    return num_players_per_position
  end

  def initialize_simulation(draft_id, picks)
    # picks = Pick.where(:draft_id => draft_id)
    #need to make league specific
    players = Recruit.where(:league_id => session[:league_id]).order('projected_points desc') 

    # sim_qbs, sim_rbs, sim_wrs, sim_tes, sim_lbs, sim_dls, sim_dbs, sim_ks, sim_hcs = queue_players(players)
    # s_qbs, s_rbs, s_wrs, s_tes, s_lbs, s_dls, s_dbs, s_ks, s_hcs = queue_players(players)
    # sim_qbs, sim_rbs, sim_wrs, sim_tes, sim_ks, sim_dsts = queue_players(players)
    # s_qbs, s_rbs, s_wrs, s_tes, s_ks, s_dsts = queue_players(players)


    # queues = { "QB" => sim_qbs, "RB" => sim_rbs, "WR" => sim_wrs, "TE" => sim_tes, "LB" => sim_lbs, "DL" => sim_dls, "DB" => sim_dbs, "K" => sim_ks, "HC" => sim_hcs }
    # s_queues = { "QB" => s_qbs, "RB" => s_rbs, "WR" => s_wrs, "TE" => s_tes, "LB" => s_lbs, "DL" => s_dls, "DB" => s_dbs, "K" => s_ks, "HC" => s_hcs }

    @queues = queue_players(players) #{ "QB" => sim_qbs, "RB" => sim_rbs, "WR" => sim_wrs, "TE" => sim_tes, "K" => sim_ks, "DEF" => sim_dsts }

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/views/drafts/_form.html.erb
<%= form_for(@draft) do |f| %>
  <% if @draft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@draft.errors.count, "error") %> prohibited this draft from being saved:</h2>

      <ul>
      <% @draft.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drafts/edit.html.erb
<h1>Editing draft</h1>

<%= render 'form' %>

<%= link_to 'Show', @draft %> |
<%= link_to 'Back', drafts_path %>

app/views/drafts/index.html.erb
<h1>Listing drafts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @drafts.each do |draft| %>
      <tr>
        <td><%= draft.name %></td>
        <td><%= link_to 'Show', draft %></td>
        <td><%= link_to 'Edit', edit_draft_path(draft) %></td>
        <td><%= link_to 'Destroy', draft, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Draft', new_draft_path %>

app/views/drafts/initialize_draft.html.erb
<% if !@message.nil? %>
	<strong><%= @message %></strong>
<% end %><br><br>

<%= form_tag("/addpick", method: "post") do %>
	<div class="field">
		<%= label_tag 'Enter next draft pick:' %><br>
		<%= text_field_tag 'player', nil, placeholder: 'Player name' %><br>
	</div>
  	<div class="actions">	
		<%= submit_tag "Submit draft pick", data: { confirm: "Submit player?" } %><br><br>
	</div>
<% end %>

<% if !@suggest_picks.nil? %>
	<%= @suggest_picks.to_s %><br><br>
	<%= "Value: " + @suggest_value.to_s %>
<% else %>
	<%= "Not your pick; no suggestions" %>
<% end %>
<br><br>

<table>
  <thead>
    <tr>
      <th>Pick Num</th>
      <th>Player</th>
      <th>Team</th>
      <th>Sim pick</th>      
    </tr>
  </thead>

  <tbody>

	<% for pick in 1..168 %>
		<% player = @picks.find_by(:pick_num => pick) %>
		<tr>
			<td><%= pick %></td>			
			<td><% if player.nil? %>
					<%= "TBD" %>
				<% else %>
					<strong><%= @sim_picks[pick][0] %></strong>
				<% end %></td>
			<td><%= @sim_picks[pick][2] %></td>
			<td><%= @sim_picks[pick][0].to_s + ", " + @sim_picks[pick][1].to_s %> </td>
		</tr>
	<% end %>
  </tbody>
</table>

app/views/drafts/live_draft.html.erb
<% @traded.each do |trade| %>
	<%= "Found: " + trade %><br>
<% end %>

<% @nottraded.each do |trade| %>
	<%= "Not Found: " + trade %><br>
<% end %>

app/views/drafts/new.html.erb
<h1>New draft</h1>

<%= render 'form' %>

<%= link_to 'Back', drafts_path %>

app/views/drafts/new_draft.html.erb
<%= form_tag "/drafts/#{@league_id}/init_draft", :method => 'post' do %>
	<div class="field">
		<%= label_tag :draft_name %>
		<%= text_field_tag :draft_name %>
	</div><br>

	<div class="field">
	    <%= label_tag :draft_type %><br>
    	<input type="radio" name="draft_type" value="Snake">Snake <br>
    	<input type="radio" name="draft_type" value="Other">Other <br>	    	
 	</div><br>	

	<div class="field">
	    <%= label_tag :my_team %><br>
	    <% @teams.each do |team| %>
	    	<input type="radio" name="my_team" value=<%= team.id %>><%= team.name %> <br>
	    <% end %>
 	</div><br>

	<div class="field">
		<%= label_tag :number_of_rounds %>
		<%= text_field_tag :number_of_rounds %>
	</div><br>

	<div class="field">
	    <% @teams.each do |team| %>
	    	<%= label_tag team.name %>
	    	<select name=<%= team.id %>>
	    		<% for i in 1..@teams.size %>
	    			<option value=<%= i.to_s %>><%= i.to_s %></option>
	    		<% end %>
	    	</select><br>
	    <% end %>
 	</div><br>

	<div class="field">
	    <%= label_tag :keepers %><br>
    	<input type="radio" name="keepers" value="Yes">Yes <br>
    	<input type="radio" name="keepers" value="No">No <br>	    	
 	</div><br>
	
	<div class="field">
	    <%= label_tag :draft_trades %><br>
    	<input type="radio" name="trades" value="Yes">Yes <br>
    	<input type="radio" name="trades" value="No">No <br>	    		    	
 	</div><br> 	

	<div class="actions">
		<%= submit_tag "Submit Draft Settings" %>
	</div> 	

<% end %>

app/views/drafts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @draft.name %>
</p>

<%= link_to 'Edit', edit_draft_path(@draft) %> |
<%= link_to 'Back', drafts_path %>

app/views/drafts/simulate_draft.html.erb
<% @simpicks.each do |num, name, position, team, points, players, flex| %>
	<%= num.to_s + ". " + name.to_s + "(" + position + "), " + team.to_s + ", " + points.to_s + ", " + players.to_s + ", " + flex.to_s %><br>
<% end %>

<% @keepers.each do |team| %>
	<% team.each do |name, round, points, cost, comp_player| %>
		<%= "Name: " + name +", Round: " + round.to_s + ", Point: " + points.to_s + ", Cost: " + cost.to_s + ", Comp player: " + comp_player %><br>
	<% end %>
<% end %>


<% for i in 0..@keeper_points.size %>
	<%= @keeper_points[i].to_s + ", " + @keeper_players[i].to_s %><br>
<% end %>